package com.example.ProductList.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "products")
@Getter
@Setter
@ApiModel(description = "data model of product entity")
public class Product {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Long id;

    @Column(columnDefinition = "VARCHAR(255)", nullable = false)
    @ApiModelProperty("product name from 5 to 50 chars")
    private String name;

    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty("product descriptions")
    private String descriptions;

    @Column(columnDefinition = "INT", nullable = false)
    private Integer kcal;

    @JsonIgnore
    @ManyToMany(mappedBy = "products", fetch = FetchType.LAZY)
    private List<ProductList> productList = new ArrayList<>();
}
